name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: vx.y.z
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: 'jdk'
          cache: 'gradle'
      
      - name: Build APK
        run: | 
          chmod +x gradlew
          ./gradlew assembleRelease
      
      - name: Set up Keystore
        run: |
          sudo apt update -y || true
          sudo apt install -y --no-install-recommends coreutils
          mkdir -p $RUNNER_TEMP/keystores
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > $RUNNER_TEMP/keystores/keystore.jks

      - name: Sign APK
        run: |
          ANDROID_SDK_PATH=$ANDROID_HOME/build-tools/35.0.0/apksigner
          $ANDROID_SDK_PATH sign \
            --ks $RUNNER_TEMP/keystores/keystore.jks \
            app/build/outputs/apk/release/app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: app-release.apk
          compression-level: 5

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Changes
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGE.md
          sparse-checkout-cone-mode: false

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: apk-artifact
      
      - name: Generate Changelog
        run: |
          cat CHANGE.md > CHANGE.txt
      
      - name: Release 
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-release.apk
          body_path: CHANGE.txt
